### ISSUE TITLE
wfc3-ir F105W bandpass has wrong format

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo.github.io#19]
Bandpass has two columns whereas the sncosmo code expects 3. I expect something went wrong in #17 . cc @jpierel14 Do you have a copy of the bandpass in the "old" format that you could make a PR for?

**Comment by jpierel14** [comment]
F105W looks like it has [3 columns ](https://github.com/sncosmo/sncosmo.github.io/blob/master/data/bandpasses/wfc3-ir/f105w.IR.tab), where are you seeing the incorrect 2 column format?

**Comment by kbarbary** [comment]
You're right. Maybe it was just my local copy. I'll check again later tonight when I'm back at my laptop.

**Comment by kbarbary** [comment]
It was a stale local copy! Sorry for the noise. Too many hours in front of a computer yesterday.
